# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Beta Build and firebase app distribution"
  lane :beta do
    match(type: 'development', readonly: is_ci, verbose: true, git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]))
    # build_app(
    #   workspace: "template.xcworkspace",
    #   configuration: "Release",
    #   scheme: "template",
    #   silent: true,
    #   clean: true,
    #   output_directory: "output",
    #   output_name: "template.ipa"
    # )

    # firebase_app_distribution(
    #     app: "1:9212010080:ios:37cc2162af5689f4132d05",
    #     firebase_cli_token: "4/1AY0e-g5g64C5mlg_LfcoBsg_HyfzXDMu2ls3jeeyS-eNr_0yDjpvZiVQJ1Y",
    #     groups: "group1",
    #     release_notes: "bugfix",
    #     debug: true
    # )
  end
end
