# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

PROJECT_NAME = "template"
XCODE_WORKSPACE = "./#{PROJECT_NAME}.xcworkspace"
OUTPUT_DIRECTORY = "./fastlane/builds"

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Beta Build and firebase app distribution"
  lane :beta do
    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      password: ENV["KEYCHAIN_PASSWORD"],
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )

    match(
      type: 'adhoc', 
      readonly: is_ci, 
      verbose: true, 
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      keychain_name: ENV["KEYCHAIN_NAME"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    clear_derived_data
    
    gym(
      scheme: ENV["PROJECT_NAME"],
      workspace: XCODE_WORKSPACE,
      clean: true,
      silent: true,
      output_directory: OUTPUT_DIRECTORY,
      output_name: "#{PROJECT_NAME}.ipa",
      export_options: {
        method: "ad-hoc",
        signingStyle: "manual",
      }
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      groups: ENV["FIREBASE_GROUP"],
      release_notes: "bugfix",
      debug: true)
  end
end
