# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Beta Build and firebase app distribution"
  lane :beta do
    gradle(
      task: "incrementVersionCode clean assembleRelease",
      properties: {
        "KEY" => ENV['ANDROID_KEY_FILE_NAME'],
        "KEY_ALIAS" => ENV['ANDROID_KEY_ALIAS'],
        "STORE_PASSWORD" => ENV['ANDROID_KEY_PASSWORD'],
        "KEY_PASSWORD" => ENV['ANDROID_KEY_PASSWORD'],
      }
    )
    
    # firebase_app_distribution(
    #   app: ENV['FIREBASE_APP'],
    #   firebase_cli_token: ENV['FIREBASE_TOKEN'],
    #   groups: ENV['FIREBASE_GROUP'],
    #   release_notes: ENV['RELEASE_NOTE'],
    #   debug: true)

    version_bump_commit();
  end

  desc "build version bump commit"
  lane :version_bump_commit do
    commit_github_file(
      repository_name: "teamlycl/action-test",
      api_token: ENV["GIT_AUTHORIZATION"],
      message: "🎉 build version bump",
      branch: "master",
      path: "../android/app/version.properties"
    )
  end
end
