name: Publish App

on: 
  push:
    branches:
      - master

env:
    NODE_VERSION: 16.x
    ANDROID_KEY_FILE: lycl.keystore
    FIREBASE_APP_GROUP: group1
    CACHE_NODE_MODULE: node_modules
    CACHE_GRADLE_WRAPPER: gradle-wrapper
    CACHE_GRADLE_CACHES: gradle-caches
    CACHE_GEM: gem-cache

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-
      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
        
  Beta-deploy-android:
    runs-on: ubuntu-latest
    needs: [init]

    steps:
      - uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ env.CACHE_GRADLE_WRAPPER }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ env.CACHE_GRADLE_CACHES }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_GRADLE_CACHES }}-
      - name: Cache Gem
        uses: actions/cache@v2
        with:
          path: ./android/vendor/bundle
          key: ${{ runner.os }}-${{ env.CACHE_GEM }}-${{ hashFiles('./android/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_GEM }}-
      - name: Generate Release Key
        run: |
          echo "${{ secrets.ANDROID_KEY }}" | base64 -d > android/app/${{ env.ANDROID_KEY_FILE }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Beta deploy using Fastlane
        run: |
          cd android
          bundle install
          bundle exec fastlane beta KEY:${{ env.ANDROID_KEY_FILE }} ALIAS:${{ secrets.ANDROID_ALIAS }} KEY_PASSWORD:${{ secrets.ANDROID_PASSWORD }} FIREBASE_APP:${{ secrets.FIREBASE_APP_ID }} FIREBASE_TOKEN:${{ secrets.FIREBASE_TOKEN }} FIREBASE_GROUP:${{ env.FIREBASE_APP_GROUP }}