name: ios beta code push

on: workflow_dispatch

env:
  NODE_VERSION: 16.x
  GIT_AUTHORIZATION: ${{ secrets.GH_TOKEN }}
  CACHE_NODE_MODULE: node_modules@v1
  CACHE_POD_MODULE: pods@v1

jobs:
  init:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

  code-push-ios-beta:
    runs-on: macOS-latest
    needs: [init]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}

      - name: Cache Pods
        uses: actions/cache@v2
        with:
          path: 'ios/Pods'
          key: ${{ runner.os }}-${{ env.CACHE_POD_MODULE }}-${{ hashFiles('ios/Podfile.lock') }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
          working-directory: 'ios'
          bundler-cache: true

      - name: Install Pods, Bundle
        run: |
          cd ios
          bundle exec pod install
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [code-push-ios-beta]
    steps:
      - name: Deploy to Codepush
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react -a dev-lycl/template-ios -d Staging
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
