name: ios beta push

on: 
  push:
    branches:
      - master

env:
    NODE_VERSION: 16.x
    CACHE_NODE_MODULE: node_modules@v1
    CACHE_POD_MODULE: pods@v1

jobs:
  init:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}
            
      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
        
  deploy-ios-beta:
    runs-on: macOS-latest
    needs: [init]

    env: 
      GIT_AUTHORIZATION: ${{ secrets.GH_TOKEN }}
      MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      FIREBASE_APP: ${{ secrets.FIREBASE_IOS_APP_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_GROUP: group1
      KEYCHAIN_NAME: lycl
      KEYCHAIN_PASSWORD: lycl_keychain_password
      ANDROID_KEY_FILE: lycl.keystore

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}

      - name: Cache Pods
        uses: actions/cache@v2
        with:
          path: 'ios/Pods'
          key: ${{ runner.os }}-${{ env.CACHE_POD_MODULE }}-${{ hashFiles('ios/Podfile.lock') }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.3"
          working-directory: "ios"
          bundler-cache: true

      - name: Install Pods, Bundle
        run: | 
          cd ios
          bundle exec pod install
          
      - name: Beta deploy using Fastlane
        run: |
          cd ios
          bundle exec fastlane beta