name: Publish App

on: 
  push:
    branches:
      - master

env:
    NODE_VERSION: 16.x
    ANDROID_KEY_FILE: lycl2.keystore

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-
      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
        
  build-android:
    runs-on: ubuntu-latest
    needs: [init]

    steps:
      - uses: actions/checkout@v2
      - name: Generate Release Key
        run: |
          echo "${{ secrets.ANDROID_KEY }}" | base64 -d > android/app/${{ env.ANDROID_KEY_FILE }}
      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleRelease -PKEY='${{ env.ANDROID_KEY_FILE }}' -PKEY_ALIAS='${{ secrets.ANDROID_ALIAS }}' -PSTORE_PASSWORD='${{ secrets.ANDROID_PASSWORD }}' -PKEY_PASSWORD='${{ secrets.ANDROID_PASSWORD }}' --stacktrace