name: Publish App
on: 
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install packages
        run: yarn install