name: Publish App

on: 
  push:
    branches:
      - master

env:
    NODE_VERSION: 16.x

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Release Key
        run: |
          echo "${{ secrets.ANDROID_KEY }}" | base64 -d > android/app/app-key.keystore
      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleRelease -PKEY='app-key.keystore' -PKEY_ALIAS='${{ secrets.ANDROID_ALIAS }}' -PSTORE_PASSWORD='${{ secrets.ANDROID_PASSWORD }}' -PKEY_PASSWORD='${{ secrets.ANDROID_PASSWORD }}' --stacktrace