name: Publish App

on: 
  push:
    branches:
      - master

env:
    NODE_VERSION: 16.x
    ANDROID_KEY_FILE: lycl.keystore
    CACHE_NODE_MODULE: node_modules
    CACHE_GRADLE_WRAPPER: gradle-wrapper
    CACHE_GRADLE_CACHES: gradle-caches

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-
      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install
        
  build-android:
    runs-on: ubuntu-latest
    needs: [init]

    steps:
      - uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.CACHE_NODE_MODULE }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ env.CACHE_GRADLE_WRAPPER }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ env.CACHE_GRADLE_CACHES }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_GRADLE_CACHES }}-
      - name: Generate Release Key
        run: |
          echo "${{ secrets.ANDROID_KEY }}" | base64 -d > android/app/${{ env.ANDROID_KEY_FILE }}
      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleRelease -PKEY='${{ env.ANDROID_KEY_FILE }}' -PKEY_ALIAS='${{ secrets.ANDROID_ALIAS }}' -PSTORE_PASSWORD='${{ secrets.ANDROID_PASSWORD }}' -PKEY_PASSWORD='${{ secrets.ANDROID_PASSWORD }}' --stacktrace