name: xmlstarlet test

on: workflow_dispatch

env:
  NODE_VERSION: 16.x

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: xmlstarlet path
        run: |
          sudo apt-get update
          sudo apt-get install xmlstarlet
          which xmlstarlet
